# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: format
        name: make format
        entry: make format
        language: system
        types: [python]
        pass_filenames: false

      - id: lint-fix
        name: make lint-fix
        entry: make lint-fix
        language: system
        types: [python]
        pass_filenames: false

      - id: mdformat
        name: make mdformat
        entry: make mdformat
        language: system
        types: [markdown]
        pass_filenames: false

      - id: typecheck
        name: make typecheck
        entry: make typecheck
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

      - id: test
        name: make test
        entry: make test
        language: system
        pass_filenames: false
        stages: [pre-push]
        always_run: true
